version: '3'

services:
  frontend:
    build: ../FALTA-UNO-FRONT
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - user-service

  user-service:
    build: ./backend/user-service
    ports:
      - "3001:3001"
    environment:
      - MONGO_URI=mongodb://mongo:27017/faltaUnoDB  # Use Docker MongoDB container name instead of localhost
    depends_on:
      - mongo

  team-service:
    build: ./backend/team-service  # Removed the trailing backslash here
    # volumes:
    #   - ./models:/app/models  # Mounts local 'models' folder to container's '/app/models'
    ports:
      - "3002:3002"
    environment:
      - MONGO_URI=mongodb://mongo:27017/faltaUnoDB
    depends_on:
      - mongo

  match-service:
    build: ./backend/match-service
    ports:
      - "3003:3003"
    environment:
      - MONGO_URI=mongodb://mongo:27017/faltaUnoDB
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db  # Volume to persist MongoDB data
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      retries: 5
      timeout: 5s
    restart: always

volumes:
  mongo-data:
